"""Agent API 相关的 Pydantic 请求 / 响应 Schema 定义。

本模块定义 Agent 接口（``/api/agent/...``）使用的所有数据模型：

- 请求：``AgentQueryRequest`` 与其约束 ``AgentConstraints``、结构化执行计划
  ``ComplexPlan``。
- 路由：``AgentRouteDecision``（由 PolicyRouter 生成的确定性路由决策）。
- 响应：``AgentQueryResponse``（含步骤轨迹 ``AgentStep``、用量 ``AgentUsage``）。
- 证据：``EvidenceItem`` / ``EvidencePack``（``rag.retrieve_evidence`` 的返回结构）。
- 工具注册：``ToolSpec``（描述 ToolRegistry 中注册的工具）。
- 会话与附件读取视图：``AgentSessionRead`` / ``AgentTurnRead`` /
  ``AttachmentRead`` / ``AttachmentChunkRead`` / ``AttachmentUploadResponse``。
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field

from app.schemas.common import Citation


class AgentConstraints(BaseModel):
    """单次请求的约束条件，用于覆盖服务端默认值。

    所有数值字段都要求严格为正（``gt=0``），确保执行器始终拥有合法执行预算。

    Per-request constraints that override server defaults.

    All numeric fields require strictly positive values so the executor
    always has a valid execution budget.
    """

    allow_external_network: bool = False  # 是否允许访问外部网络（默认 False，仅使用本地工具）
    max_steps: int = Field(default=8, gt=0)  # 最大执行步数（必须 >0，默认 8）
    max_tool_calls: int = Field(default=5, gt=0)  # 最大工具调用次数（必须 >0，默认 5）
    budget_tokens: int = Field(default=20000, gt=0)  # token 预算上限（必须 >0，默认 20000）
    timeout_seconds: int = Field(default=45, gt=0)  # 执行超时秒数（必须 >0，默认 45）


class AgentQueryRequest(BaseModel):
    """Agent 查询请求体（``POST /api/agent/query``）。

    Request body for POST /api/agent/query.
    """

    project_slug: str  # 目标项目 slug（必填）
    query: str  # 用户查询内容（必填）
    session_id: str | None = None  # 会话 ID（可空；为空时由服务端创建新会话）
    document_id: str | None = None  # 限定检索范围的文档 ID（可空）
    compare_document_ids: list[str] = Field(
        default_factory=list,
        max_length=5,
        description=(
            "Optional explicit comparison scope. When provided, retrieval is "
            "strictly limited to these 1-5 ready documents."
        ),
    )
    compare_dimensions: list[str] = Field(
        default_factory=list,
        max_length=12,
        description=(
            "Optional comparison dimensions. Empty means the bounded default "
            "dimension set is used."
        ),
    )
    constraints: AgentConstraints = Field(default_factory=AgentConstraints)  # 执行约束（默认取 AgentConstraints 默认值）


class ComplexPlan(BaseModel):
    """面向 ``complex_multi_hop`` 查询的结构化、可审计计划元数据。

    这是一个有边界、确定性的计划 —— 并非由 LLM 生成。执行器根据路由约束与已注册的
    白名单工具构建它，所有字段在轨迹步骤与 SSE 流中可见，便于审计。

    Structured, auditable plan metadata for complex_multi_hop queries.

    This is a bounded, deterministic plan — it is NOT generated by an LLM.
    The executor builds it from route constraints and the registered
    whitelist tools.  Every field is visible in trace steps and SSE
    streaming for auditability.
    """

    plan_type: str = "controlled_complex"  # 计划类型标识（默认 "controlled_complex"）
    allowed_tools: list[str] = Field(  # 允许调用的白名单工具列表
        default_factory=lambda: [
            "rag.retrieve_evidence",
            "rag.answer",
            "answer.synthesize",
            "answer.verify",
        ]
    )
    forbidden_tools: list[str] = Field(  # 明确禁止的工具列表（黑名单）
        default_factory=lambda: [
            "shell",
            "sql",
            "write",
            "network",
            "file_system_write",
            "arbitrary_code_execution",
        ]
    )
    max_steps: int = 8  # 最大步数（默认 8）
    max_tool_calls: int = 5  # 最大工具调用次数（默认 5）
    subtasks: list[str] = Field(  # 子任务步骤序列（默认：检索证据 → RAG 回答 → 综合 → 校验）
        default_factory=lambda: [
            "retrieve_evidence",
            "rag_answer",
            "synthesize",
            "verify",
        ]
    )


class AgentRouteDecision(BaseModel):
    """由 PolicyRouter 生成的确定性路由决策。

    公开的路由类型：
      - ``simple_rag`` —— 默认单源 RAG
      - ``evidence_required`` —— 查询要求引用 / 来源
      - ``table_or_metric`` —— 查询预期返回数值 / 表格数据
      - ``multi_source_compare`` —— 查询要求比较两个及以上对象
      - ``complex_multi_hop`` —— 多部分 / 多跳 / 链式推理
      - ``needs_clarification`` —— 空查询或无法回答的查询

    Deterministic routing decision produced by PolicyRouter.

    Public route types:
      - ``simple_rag`` — default single-source RAG
      - ``evidence_required`` — query asks for citations / sources
      - ``table_or_metric`` — query likely expects numeric / tabular data
      - ``multi_source_compare`` — query asks to compare two or more items
      - ``complex_multi_hop`` — multi-part / multi-hop / chained reasoning
      - ``needs_clarification`` — empty or unanswerable query
    """

    route: str  # 最终路由类型（取值见上方文档）
    requires_citations: bool = True  # 是否需要引用 / 来源（默认 True）
    max_retries: int = 0  # 最大重试次数（默认 0）
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)  # 路由置信度（0~1，默认 1.0）
    reason: str = ""  # 路由决策的原因说明（默认为空字符串）


class AgentStep(BaseModel):
    """Agent 执行轨迹中的单个步骤。

    A single step inside the agent execution trace.
    """

    step_id: int  # 步骤序号
    step_type: str  # 步骤类型："route" | "plan" | "retrieve" | "tool_call" | "generate" | "synthesis" | "finalize"
    summary: str  # 步骤摘要说明
    latency_ms: int | None = None  # 该步骤耗时（毫秒，可空）
    tool_name: str | None = None  # 调用的工具名称（仅工具调用步骤，可空）
    tool_ok: bool | None = None  # 工具调用是否成功（可空）
    metadata: dict[str, Any] = Field(default_factory=dict)  # 步骤附加元数据


class AgentUsage(BaseModel):
    """一次 Agent 执行的 token 与调用用量汇总。

    Token and call usage summary for an agent run.
    """

    prompt_tokens: int = 0  # 提示词（prompt）token 数
    completion_tokens: int = 0  # 生成（completion）token 数
    tool_calls: int = 0  # 工具调用次数
    steps: int = 0  # 步骤数


class AgentQueryResponse(BaseModel):
    """Agent 查询响应体（``POST /api/agent/query``）。

    v2a 在保持 v1 兼容的同时新增 ``route`` 与 ``warnings``；
    v3 新增 ``trace_id``、``answer_provider``、``answer_model``。

    Response body for POST /api/agent/query.

    v2a adds ``route`` and ``warnings`` while preserving v1 compatibility.
    v3 adds ``trace_id``, ``answer_provider``, and ``answer_model``.
    """

    request_id: str  # 请求 ID
    session_id: str  # 会话 ID
    status: str  # 执行状态："completed" | "max_steps" | "timeout" | "error"
    final_answer: str  # 最终回答（Markdown 文本）
    citations: list[Citation] = Field(default_factory=list)  # 引用来源列表
    steps: list[AgentStep] = Field(default_factory=list)  # 执行轨迹步骤
    usage: AgentUsage = Field(default_factory=AgentUsage)  # 用量汇总
    route: AgentRouteDecision | None = None  # 路由决策详情（可空）
    warnings: list[str] = Field(default_factory=list)  # 执行告警信息列表
    trace_id: str | None = None  # 轨迹 ID（可空）
    answer_provider: str = "local"  # 生成回答的模型提供商（默认 "local"）
    answer_model: str = "local-fallback"  # 生成回答的模型名（默认 "local-fallback"）
    comparison: "ComparisonPack | None" = None


class EvidenceItem(BaseModel):
    """一条携带元数据的检索证据。

    ``source_stage`` 指明该证据由哪条检索路径产出。建议取值：``document_table``、
    ``document_figure``、``profile_term``、``claim``、``source_chunk`` 或
    ``unknown``。

    ``support_hint`` 是尽力而为的确定性标签：``direct`` 表示证据直接回答问题，
    ``contextual`` 表示提供支持性上下文，``weak`` 表示匹配置信度低。

    A single piece of retrieved evidence with metadata.

    ``source_stage`` indicates which retrieval path produced the item.
    Suggested values: ``document_table``, ``document_figure``,
    ``profile_term``, ``claim``, ``source_chunk``, or
    ``unknown``.

    ``support_hint`` is a best-effort deterministic label: ``direct``
    when the evidence directly addresses the question, ``contextual``
    when it provides supporting context, or ``weak`` when the match is
    low-confidence.
    """

    index: int  # 证据在列表中的序号
    document_id: str | None = None  # 来源文档 ID（可空）
    chunk_id: str | None = None  # 来源分块 ID（可空）
    attachment_id: str | None = None  # 来源会话附件 ID（可空）
    page_slug: str | None = None  # 规范化页面的 slug（可空）
    page_title: str | None = None  # 规范化页面的标题（可空）
    page_kind: str | None = None  # 页面类型（可空）
    page_label: str | None = None  # 页码标签（可空）
    score: float = 0.0  # 检索相关度分数
    excerpt: str = ""  # 证据摘录文本
    context_text: str = ""  # 附加上下文文本
    parse_version: str | None = None  # 所属解析版本（可空）
    parent_chunk_id: str | None = None  # 父块 ID（可空）
    block_type: str | None = None  # 内容块类型（可空）
    source_spans: list[dict[str, Any]] = Field(default_factory=list)  # 源文本位置区间列表
    asset_id: str | None = None  # 资源 ID（可空）
    table_id: str | None = None  # 表格 ID（可空）
    figure_id: str | None = None  # 插图 ID（可空）
    formula_id: str | None = None  # 公式 ID（可空）
    evidence_kind: str | None = None  # 证据种类（可空）
    source_stage: str = "unknown"  # 产出该证据的检索路径（默认 "unknown"）
    support_hint: str = "weak"  # 支持程度提示（默认 "weak"）
    comparison_paper_id: str | None = None
    comparison_dimension: str | None = None


COMPARISON_DIMENSIONS: tuple[str, ...] = (
    "method/architecture",
    "retrieval unit/data representation",
    "training objective",
    "datasets/tasks",
    "metrics/results",
    "limitations/use cases",
)


class ComparisonPaper(BaseModel):
    document_id: str
    title: str
    ordinal: int = 0


class ComparisonEvidenceCell(BaseModel):
    paper_id: str
    paper_title: str
    dimension: str
    status: Literal["supported", "missing", "conflict"] = "missing"
    evidence_indexes: list[int] = Field(default_factory=list)
    citation_indexes: list[int] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    notes: list[str] = Field(default_factory=list)


class ComparisonEdge(BaseModel):
    id: str | None = None
    source_type: str
    source_id: str
    relation_type: str
    target_type: str
    target_id: str
    document_id: str | None = None
    parse_version: str | None = None
    evidence_chunk_id: str | None = None
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)


class ComparisonPack(BaseModel):
    mode: Literal["cross_paper", "intra_paper", "candidate_selection"] = "cross_paper"
    explicit_scope: bool = False
    papers: list[ComparisonPaper] = Field(default_factory=list)
    dimensions: list[str] = Field(default_factory=list)
    cells: list[ComparisonEvidenceCell] = Field(default_factory=list)
    edges: list[ComparisonEdge] = Field(default_factory=list)
    missing_cells: list[str] = Field(default_factory=list)
    conflict_cells: list[str] = Field(default_factory=list)
    candidate_document_ids: list[str] = Field(default_factory=list)
    status: Literal["ready", "partial", "needs_selection"] = "ready"


# ``AgentQueryResponse`` is declared before the comparison models for API
# documentation readability.  Resolve that forward reference once the models
# are available so non-null comparison payloads validate on every Pydantic
# version used by the service and test suite.
AgentQueryResponse.model_rebuild()


class TableFactEvidence(BaseModel):
    """Exact table value preserved for answer and Agent synthesis.

    ``fact_id`` 是稳定的事实标识（table + row + column + value 哈希）；
    ``unit`` 从 value 尾部解析（如 "21.0%" 的 "%"），无单位时为空；
    ``term`` 是该事实的指标术语（取 column 列名），供期望 facts 遗漏校验使用。
    """

    table_id: str
    document_id: str | None = None
    parse_version: str | None = None
    row_label: str = ""
    column: str
    value: str
    row_index: int = 0
    source_chunk_ids: list[str] = Field(default_factory=list)
    fact_id: str = ""
    unit: str = ""
    term: str = ""


class TableCoverage(BaseModel):
    """Per-table coverage metadata mirrored from the canonical typed inventory.

    9.7.1：每表至少保留 canonical manifest 已有的轻量覆盖元数据，不注入
    完整 manifest 或 child 文本。``row_indices`` 是该表在 inventory 中的
    全部行索引，供下游与已返回 table_facts 的行做覆盖比较。
    """

    document_id: str = ""
    parse_version: str = ""
    table_id: str = ""
    row_count: int = 0
    source_block_ids: list[str] = Field(default_factory=list)
    child_ids: list[str] = Field(default_factory=list)
    child_count: int = 0
    parent_ids: list[str] = Field(default_factory=list)
    row_indices: list[int] = Field(default_factory=list)


class EvidencePack(BaseModel):
    """``rag.retrieve_evidence`` 返回的仅检索证据集合。

    ``status`` 表示结果状态：``ok`` 表示检索到证据、``project_not_found`` 表示项目
    slug 未知、``empty`` 表示未找到匹配证据。

    Retrieve-only evidence collection returned by ``rag.retrieve_evidence``.

    ``status`` indicates the outcome: ``ok`` when evidence was found,
    ``project_not_found`` when the project slug is unknown, or
    ``empty`` when no matching evidence was found.

    ``inventory`` / ``coverage_status`` / ``coverage_missing_tables``（9.7）：
    表格覆盖元数据。``coverage_status`` 取值 complete / partial / unknown；
    旧调用方不提供这些字段时默认 unknown，避免用空列表同时表示"没有表"和
    "尚未计算"。coverage 门禁只对 partial 生效（见 agent_executor 直通门禁）。
    """

    status: str = "empty"  # 检索结果状态（默认 "empty"）
    items: list[EvidenceItem] = Field(default_factory=list)  # 检索到的证据条目


    table_facts: list[TableFactEvidence] = Field(default_factory=list)

    # 9.7：轻量 typed inventory / coverage 通道（旧调用方缺省时 unknown 兼容）
    inventory: list[TableCoverage] = Field(default_factory=list)
    coverage_status: str = "unknown"  # complete | partial | unknown
    coverage_missing_tables: list[str] = Field(default_factory=list)
    comparison: ComparisonPack | None = None


class ToolSpec(BaseModel):
    """描述 ToolRegistry 中注册的某个工具的 Schema。

    Schema describing a tool registered in the ToolRegistry.
    """

    name: str  # 工具名称
    description: str  # 工具描述
    input_schema: dict[str, Any]  # 工具输入参数 Schema
    output_schema: dict[str, Any] | None = None  # 工具输出 Schema（可空）
    auth_scope: list[str] = Field(default_factory=lambda: ["tool:invoke"])  # 调用所需授权范围（默认 ["tool:invoke"]）
    side_effect_level: str = "none"  # 副作用等级："none" | "read" | "write"
    timeout_ms: int = 15000  # 工具调用超时（毫秒，默认 15000）


class AgentSessionRead(BaseModel):
    """Agent 对话会话的只读摘要。

    Read-only summary of an Agent conversation session.
    """

    id: str  # 会话 ID
    project_slug: str  # 所属项目 slug
    scope_type: str  # 会话范围类型："project" | "document"
    document_id: str | None = None  # 限定文档 ID（可空）
    document_title: str | None = None  # 限定文档标题（可空）
    preview: str  # 会话内容预览
    turn_count: int  # 轮次数
    created_at: str  # 创建时间（字符串）
    updated_at: str  # 最近更新时间（字符串）
    expires_at: str  # 过期时间（字符串）


class AgentTurnRead(BaseModel):
    """Agent 对话会话中的单个有序轮次。

    A single ordered turn inside an Agent conversation session.
    """

    turn_index: int  # 轮次序号
    role: str  # 角色："user" | "agent" | "tool"
    content: str  # 该轮内容
    tool_name: str | None = None  # 工具名称（可空）
    tool_args: dict[str, Any] | None = None  # 工具调用参数（可空）
    tool_result: str | None = None  # 工具调用结果（可空）
    step_type: str | None = None  # 步骤类型（可空）
    citations: list[dict[str, Any]] = Field(default_factory=list)  # 引用来源列表
    created_at: str  # 创建时间（字符串）


class AttachmentChunkRead(BaseModel):
    """会话范围内临时附件的单个分块。

    A single chunk from a session-scoped temporary attachment.
    """

    id: str  # 分块 ID
    ordinal: int  # 顺序号
    heading: str | None = None  # 标题（可空）
    page_label: str | None = None  # 页码标签（可空）
    text: str  # 文本内容
    token_estimate: int  # 估算 token 数


class AttachmentRead(BaseModel):
    """会话范围内临时附件的摘要。

    Summary of a session-scoped temporary attachment.
    """

    id: str  # 附件 ID
    session_id: str  # 所属会话 ID
    project_slug: str  # 所属项目 slug
    file_name: str  # 文件名
    title: str | None = None  # 标题（可空）
    sha256: str  # 文件 SHA-256 哈希
    byte_size: int  # 文件字节数
    status: str  # 附件状态
    chunk_count: int  # 分块数量
    created_at: str  # 创建时间（字符串）
    updated_at: str  # 最近更新时间（字符串）


class AttachmentUploadResponse(BaseModel):
    """``POST /api/agent/sessions/{id}/attachments`` 的响应体。

    Response body for POST /api/agent/sessions/{id}/attachments.
    """

    attachment: AttachmentRead  # 上传后的附件摘要
    chunks: list[AttachmentChunkRead]  # 附件切分后的分块列表
    message: str = "Attachment stored for this session."  # 提示信息（保留原有默认字符串）
