from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from app.schemas.common import Citation


class AgentConstraints(BaseModel):
    """Per-request constraints that override server defaults.

    All numeric fields require strictly positive values so the executor
    always has a valid execution budget.
    """

    allow_external_network: bool = False
    max_steps: int = Field(default=8, gt=0)
    max_tool_calls: int = Field(default=5, gt=0)
    budget_tokens: int = Field(default=20000, gt=0)
    timeout_seconds: int = Field(default=45, gt=0)


class AgentQueryRequest(BaseModel):
    """Request body for POST /api/agent/query."""

    project_slug: str
    query: str
    session_id: str | None = None
    constraints: AgentConstraints = Field(default_factory=AgentConstraints)


class ComplexPlan(BaseModel):
    """Structured, auditable plan metadata for complex_multi_hop queries.

    This is a bounded, deterministic plan — it is NOT generated by an LLM.
    The executor builds it from route constraints and the registered
    whitelist tools.  Every field is visible in trace steps and SSE
    streaming for auditability.
    """

    plan_type: str = "controlled_complex"
    allowed_tools: list[str] = Field(
        default_factory=lambda: [
            "rag.retrieve_evidence",
            "rag.answer",
            "answer.synthesize",
            "answer.verify",
        ]
    )
    forbidden_tools: list[str] = Field(
        default_factory=lambda: [
            "shell",
            "sql",
            "write",
            "network",
            "file_system_write",
            "arbitrary_code_execution",
        ]
    )
    max_steps: int = 8
    max_tool_calls: int = 5
    subtasks: list[str] = Field(
        default_factory=lambda: [
            "retrieve_evidence",
            "rag_answer",
            "synthesize",
            "verify",
        ]
    )


class AgentRouteDecision(BaseModel):
    """Deterministic routing decision produced by PolicyRouter.

    Public route types:
      - ``simple_rag`` — default single-source RAG
      - ``evidence_required`` — query asks for citations / sources
      - ``table_or_metric`` — query likely expects numeric / tabular data
      - ``multi_source_compare`` — query asks to compare two or more items
      - ``complex_multi_hop`` — multi-part / multi-hop / chained reasoning
      - ``needs_clarification`` — empty or unanswerable query
    """

    route: str
    requires_citations: bool = True
    max_retries: int = 0
    confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    reason: str = ""


class AgentStep(BaseModel):
    """A single step inside the agent execution trace."""

    step_id: int
    step_type: str  # "route" | "plan" | "retrieve" | "tool_call" | "generate" | "synthesis" | "finalize"
    summary: str
    latency_ms: int | None = None
    tool_name: str | None = None
    tool_ok: bool | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class AgentUsage(BaseModel):
    """Token and call usage summary for an agent run."""

    prompt_tokens: int = 0
    completion_tokens: int = 0
    tool_calls: int = 0
    steps: int = 0


class AgentQueryResponse(BaseModel):
    """Response body for POST /api/agent/query.

    v2a adds ``route`` and ``warnings`` while preserving v1 compatibility.
    v3 adds ``trace_id``, ``answer_provider``, and ``answer_model``.
    """

    request_id: str
    session_id: str
    status: str  # "completed" | "max_steps" | "timeout" | "error"
    final_answer: str
    citations: list[Citation] = Field(default_factory=list)
    steps: list[AgentStep] = Field(default_factory=list)
    usage: AgentUsage = Field(default_factory=AgentUsage)
    route: AgentRouteDecision | None = None
    warnings: list[str] = Field(default_factory=list)
    trace_id: str | None = None
    answer_provider: str = "local"
    answer_model: str = "local-fallback"


class EvidenceItem(BaseModel):
    """A single piece of retrieved evidence with metadata.

    ``source_stage`` indicates which retrieval path produced the item.
    Suggested values: ``document_table``, ``document_figure``,
    ``profile_term``, ``claim``, ``source_chunk``, ``wiki_page``, or
    ``unknown``.

    ``support_hint`` is a best-effort deterministic label: ``direct``
    when the evidence directly addresses the question, ``contextual``
    when it provides supporting context, or ``weak`` when the match is
    low-confidence.
    """

    index: int
    document_id: str | None = None
    chunk_id: str | None = None
    page_slug: str | None = None
    page_title: str | None = None
    page_kind: str | None = None
    page_label: str | None = None
    score: float = 0.0
    excerpt: str = ""
    evidence_kind: str | None = None
    source_stage: str = "unknown"
    support_hint: str = "weak"


class EvidencePack(BaseModel):
    """Retrieve-only evidence collection returned by ``rag.retrieve_evidence``.

    ``status`` indicates the outcome: ``ok`` when evidence was found,
    ``project_not_found`` when the project slug is unknown, or
    ``empty`` when no matching evidence was found.
    """

    status: str = "empty"
    items: list[EvidenceItem] = Field(default_factory=list)


class ToolSpec(BaseModel):
    """Schema describing a tool registered in the ToolRegistry."""

    name: str
    description: str
    input_schema: dict[str, Any]
    output_schema: dict[str, Any] | None = None
    auth_scope: list[str] = Field(default_factory=lambda: ["tool:invoke"])
    side_effect_level: str = "none"  # "none" | "read" | "write"
    timeout_ms: int = 15000


class AgentSessionRead(BaseModel):
    """Read-only summary of an Agent conversation session."""

    id: str
    project_slug: str
    turn_count: int
    created_at: str
    updated_at: str
    expires_at: str


class AgentTurnRead(BaseModel):
    """A single ordered turn inside an Agent conversation session."""

    turn_index: int
    role: str
    content: str
    tool_name: str | None = None
    tool_args: dict[str, Any] | None = None
    tool_result: str | None = None
    step_type: str | None = None
    created_at: str
